export const cards = [
    {
        id:1,
        name:"XYZ",
        updated:"26/04/2019",
        lesson:"3",
        time:"40",
        stat:"Live",
        tags:[
            "learning","coding"
        ],
        teams:"Alpha"
    },
    {
        name:"batists",
        updated:"26/04/2019",
        lesson:"3",
        time:"40",
        stat:"Draft",
        tags:[
            "baking","programming"
        ],
        teams:"Alpha"
    },
    {
        name:"Halloween",
        updated:"26/04/2019",
        lesson:"3",
        time:"36",
        stat:"Archive",
        tags:[
            "learning","yoga","health"
        ],
        teams:"Beta"
    },
    {
        name:"tesla",
        updated:"07/04/2021",
        lesson:"3",
        time:"48",
        stat:"Archive",
        tags:[
            "hacking","programming"
        ],
        teams:"Alpha"
    },
    {
        name:"zing",
        updated:"26/04/2019",
        lesson:"3",
        time:"40",
        stat:"Live",
        tags:[
            "learning","gym","Body"
        ],
        teams:"Bravo"
    },
    {
        name:"pappot",
        updated:"26/04/2014",
        lesson:"3",
        time:"90",
        stat:"Archive",
        tags:[
            "Photography","programming"
        ],
        teams:"Bravo"
    }
]